# Simulate data in the same form as sitrep from a very simple branching process model
# The purpose of this is to evaluate the performance of the negative binomials regressions 
# approach used in figure 3 for evaluating who is infecting whom.



draw_generation_interval<-function(n){
  # n is the number of generation intervals to draw
  # For now, base generation time estimates on Ferretti  (Science 2020)
  # Weibull shape = 2.826
  w_shape<-2.826
  # Weibull scale = 5.665
  w_scale<- 5.665
  gen_int<-rweibull(n,shape = w_shape,scale=w_scale)
  #  gen_int<-rep(7,n)
  return(gen_int)
}


sim_data_for_one_trust<-function(community_onset_admissions, hcws_infected_in_community){
  # community_onset_admissions is a vector with length equal to the number of days to simulate
  # ith element contains number of patients with community onset covid (still infectious) admitted on day i
  # hcws_infected_in_community is similar for infections in HCWs acquired in the community
  #function simulated number of days equal to length(community_onset_admissions)
  # and returns a a dataframe holding number of different of infctions in the different groups on each day
  MAXGI<-20  #max permitted generation interval
  days<-length(community_onset_admissions)
  ha_infections_P <-rep(0,days + MAXGI ) #hospital acquired infections in patients
  ha_infections_H <-rep(0,days + MAXGI ) #hospital acquired infections in HCWs
  
  for(i in 1:days){
    # total secondary cases from community onset admissions
    if(community_onset_admissions[i]>0){
      y_C <-rnbinom(community_onset_admissions[i],mu=R_CH + R_CP, size=k_C)
      if(sum(y_C)>0){
        gis<-draw_generation_interval(sum(y_C))
        patient_infections<-rbinom(sum(y_C),1,R_CP/(R_CH+R_CP))
        HCW_infections<-1-patient_infections
        for(j in 1:length(gis)){
          if(patient_infections[j]) ha_infections_P[i+gis[j]]<- ha_infections_P[i+gis[j]] +1
          if(HCW_infections[j]) ha_infections_H[i+gis[j]]<- ha_infections_H[i+gis[j]] +1
        }  # end for
      }# end if(sum_ycC) 
    }# end if(community_onset_admissions)
    
    # total secondary cases from community transmission to HCWs
    if(hcws_infected_in_community[i]>0){
      y_C <-rnbinom(hcws_infected_in_community[i],mu=R_HH + R_HP, size=k_H)
      if(sum(y_C)>0){
        gis<-draw_generation_interval(sum(y_C))
        patient_infections<-rbinom(sum(y_C),1,R_HP/(R_HH+R_HP))
        HCW_infections<-1-patient_infections
        for(j in 1:length(gis)){
          if(patient_infections[j]) ha_infections_P[i+gis[j]]<- ha_infections_P[i+gis[j]] +1
          if(HCW_infections[j]) ha_infections_H[i+gis[j]]<- ha_infections_H[i+gis[j]] +1
        }  # end for
      }# end if(sum_ycC) 
    }# end if(community_onset_admissions)
    
    # total secondary cases from  patients who acquired infection in hospital
    if(ha_infections_P[i]>0){
      y_C <-rnbinom(ha_infections_P[i],mu=R_PH + R_PP, size=k_P)
      if(sum(y_C)>0){
        gis<-draw_generation_interval(sum(y_C))
        patient_infections<-rbinom(sum(y_C),1,R_PP/(R_PH+R_PP))
        HCW_infections<-1-patient_infections
        for(j in 1:length(gis)){
          if(patient_infections[j]) ha_infections_P[i+gis[j]]<- ha_infections_P[i+gis[j]] +1
          if(HCW_infections[j]) ha_infections_H[i+gis[j]]<- ha_infections_H[i+gis[j]] +1
        }  # end for
      }# end if(sum_ycC) 
    }# end if(community_onset_admissions)
    
    # total secondary cases from  HCWs who acquired infection in this hospital
    if(ha_infections_H[i]>0){
      y_C <-rnbinom(ha_infections_H[i],mu=R_HH + R_HP, size=k_H)
      if(sum(y_C)>0){
        gis<-draw_generation_interval(sum(y_C))
        patient_infections<-rbinom(sum(y_C),1,R_HP/(R_HH+R_HP))
        HCW_infections<-1-patient_infections
        for(j in 1:length(gis)){
          if(patient_infections[j]) ha_infections_P[i+gis[j]]<- ha_infections_P[i+gis[j]] +1
          if(HCW_infections[j]) ha_infections_H[i+gis[j]]<- ha_infections_H[i+gis[j]] +1
        }  # end for
      }# end if(sum_ycC) 
    }# end if(community_onset_admissions)
  }
  
  
  l<-length(hcws_infected_in_community)
  total_infections_H<-ha_infections_H[1:l]
  total_infections_H<- total_infections_H +hcws_infected_in_community
  results<-data.frame(ca_P=community_onset_admissions[1:l],ha_P=ha_infections_P[1:l], ha_H=ha_infections_H[1:l], total_H=total_infections_H)  
  return(results)
}


# to generate data like that we analyse we now need to filter output of sim_data_for_one_trust
# so that 
# i)  we only observe infections with a certain probability 
# ii) we aggregate data into periods of x days 
# Need two new functions to do this 

gen_observed_data<-function(rawdata, prob_observing_patient_infection, prob_observing_hcw_infection){
  #rawdata is a adataframe generated by sim_data_for_one_trust
  #prob_observing_patient_infection and prob_observing_hcw_infection correspond to p_P and p_H
  n<-dim(rawdata)[1]
  obs_ha_P<-rbinom(rep(1,n), rawdata$ha_P,prob_observing_patient_infection) 
  obs_ha_H<-rbinom(rep(1,n), rawdata$ha_H,prob_observing_hcw_infection)
  obs_total_H<-rbinom(rep(1,n), rawdata$total_H,prob_observing_hcw_infection)
  obs_ca_P<-rawdata$ca_P   #i.e. for now assume that all those patients admitted with covid are detected 
                           # (not unreasonable for periods where admission screening was in place)
  results<-data.frame(o_ca_P= obs_ca_P,o_ha_P=obs_ha_P, o_ha_H=obs_ha_H, o_total_H=obs_total_H)  
  return(results)
}
 
gen_wkly_total<-function(daily.data, daysinweek=7){
  #function takes a data frame containing daily data,daily.data assumed to be output from gen_observed_data
  #and returns weekly aggregates (i.e. total for each variable for each "week")
  # by default  assumes 7 days in a week, but allows for other possibilities so we can, for example, generate 
  # aggregates at 5 day intervals, which could better reflect the generation interval
  l<- dim(daily.data)[1]
  m<-dim(daily.data)[2]
  daily.data$wk<- 1+(0:(l-1))%/%daysinweek   # adds a week number field, wk
  result<-aggregate(daily.data[,1:m], by=list(week=daily.data$wk), sum, simplify=TRUE)
  return(result)
}

# Parameters for regression model

R_HH <- 0.5 #mean secondary cases amongst HCWs per case in a HCW
R_HP <- 0.2 #mean secondary cases amongst in-patients per case in a HCW
R_HC <-  NA #not currently used. mean secondary cases in community  per case in a HCW

R_PH <- 0.2 #mean secondary cases amongst HCWs per nosocomial case in a patient
R_PP <- 0.6 #mean secondary cases amongst in-patients per nosocomial case in a patient
R_PC <-  NA #not currently used. mean secondary cases in community  per nosocomial case in a patient

R_CH <- 0.05 #mean secondary cases amongst HCWs via hospital spread per admitted community acquired case in a patient
R_CP <- 0.05 #mean secondary cases amongst in-patients per admitted community acquired case
R_CC <-  NA #not currently used. mean secondary cases in community  per admitted community acquired case


# then just need detection probabilities

p_P<- 1# probability that a patient infected in hospital is detected and recorded as a nosocomial case
p_H <-1  # probability that an infected HCW is detected
p_C <- 1 # probablity that a patient admitted with community onset COVID-19 is detected and recorded in the data


# in general this varies over time and space but Max Lau 2020 PNAS paper (Lau, Grenfell, ...Lopman)
# suggests values of 0.5 are reasonable https://www.pnas.org/content/117/36/22430.short

k_C <- 0.5 # clustering parameter for negbin distribution for  secondary cases from CA patients
k_P <- 0.5 # clustering parameter for negbin distribution for  secondary cases from HA patients
k_H <- 0.5 # clustering parameter for negbin distribution for  secondary cases from HCWs


community_onset_admissions<-as.integer(10*runif(1000))
hcws_infected_in_community<-as.integer(20*runif(1000))

raw_sim1<-sim_data_for_one_trust(community_onset_admissions,hcws_infected_in_community)
# raw_sim1 now holds information on number of patients and HCWs infected on each day

obs_sim1<-gen_observed_data(raw_sim1,prob_observing_patient_infection=p_P,prob_observing_hcw_infection=p_H)
obs_sim1_weekly<-gen_wkly_total(obs_sim1)
obs_sim1_5dayweekly<-gen_wkly_total(obs_sim1, daysinweek = 5)

# now try approach generating data that looks like real data, using sitrep data as input

sitrep<-sitreps_eng_expanded <- readRDS("~/Dropbox/studies/covid19/nosocomial transmission stuff/sitrep/final_analysis/create_dfs/sitreps_eng_expanded.rds")
sitrep<-subset(sitrep, organisation_type=="Acute Trust", select=c(date,region,org_code,org_name, organisation_type, n_inpatients_diagnosed,
                                                                  n_inpatients_diagnosed_0_2, n_inpatients_diagnosed_3_7,  n_inpatients_diagnosed_8_14, 
                                                                  n_inpatients_diagnosed_15_ , n_inpatients_diagnosed_asymptomatic, n_patients_admitted_first, n_patients_admitted_readmitted,  
                                                                  n_care_home_diagnosed, n_care_home_admitted, n_patients_admitted, n_beds_mechanical, n_beds_noninvasive, n_beds_oxygenation, 
                                                                  n_nhs_staff_bed_covid19, n_beds_other_3, n_staff_absent_covid_1, n_staff_absent_1, n_staff_absent_2, hospital_prev, icu_prev,non_cov_ns_prev, 
                                                                  hcwcovid_daily_isolated1,hcwcovid_daily_isolated2,hcwcovid_daily_isolated3,hcwcovid_daily_isolated4,
                                                                  hcwcovid_daily_isolated5,hcwcovid_daily_isolated6,hcwcovid_daily_isolated7,hcwcovid_daily_isolated8,
                                                                  hcwcovid_daily_isolated9,hcwcovid_daily_isolated10,smoothed_hcwcovid_daily_isolated))  

include<-!(sitrep$org_code %in% c("RP4" , "RBS", "RCU"))
sitrep<-sitrep[include,]
# These excludes these children-only hospitals 
# "GREAT ORMOND STREET HOSPITAL FOR CHILDREN NHS FOUNDATION TRUST" 
# "ALDER HEY CHILDREN'S NHS FOUNDATION TRUST" 
# “SHEFFIELD CHILDREN'S NHS FOUNDATION TRUST" 
sitrep$ca_cases<-sitrep$n_inpatients_diagnosed_0_2 + sitrep$n_patients_admitted # community-acquired cases
trust_codes<-unique(sitrep$org_code)


# initially do some test plots for the first trust 
sel<-sitrep$org_code==trust_codes[1] & !is.na(sitrep$ca_cases)

ca_admissions<-sitrep$ca_cases[sel] 
days<-sitrep$date[sel]
hcws_infected_in_community<-rep(0,length(days))
  
#now, starting at day 200, use  ca_admissions as input for simulating hospital data up to time 400
# then use 100 days data starting from 251 for simulations, generating weekly partially observed data  
# Do this for both 7 day and 5 days "weeks" 
raw_sim1<-sim_data_for_one_trust(ca_admissions,hcws_infected_in_community)
# raw_sim1 now holds information on number of patients and HCWs infected on each day
obs_sim1<-gen_observed_data(raw_sim1,prob_observing_patient_infection=0.2,prob_observing_hcw_infection=0.9)
obs_sim1_weekly<-gen_wkly_total(obs_sim1)
obs_sim1_5dayweekly<-gen_wkly_total(obs_sim1, daysinweek = 5)

plot(obs_sim1_5dayweekly$o_ca_P, type='l')
lines(obs_sim1_5dayweekly$o_ha_P, col='blue')
lines(obs_sim1_5dayweekly$o_ha_P, col='pink')
lines(obs_sim1_5dayweekly$o_ha_P, col='blue')
lines(obs_sim1_5dayweekly$o_ha_H, col='pink')
lines(obs_sim1_5dayweekly$o_total_H, col='red')

# now create data from holding simulations for the trusts 2:100  
obs_sim1_weekly$trust<-trust_codes[1]
obs_sim1_5dayweekly$trust<-trust_codes[1]
for(i in 2:100){
  print(i)
  sel<-sitrep$org_code==trust_codes[i] & !is.na(sitrep$ca_cases)
  if(sum(sel)>50){
    ca_admissions<-sitrep$ca_cases[sel] 
    ca_admissions<-rpois(length(ca_admissions),2) # for now try Poisson admissions, mean 2
    days<-sitrep$date[sel]
    hcws_infected_in_community<-rep(0,length(days))
    raw_sim1<-sim_data_for_one_trust(ca_admissions,hcws_infected_in_community)
    # raw_sim1 now holds information on number of patients and HCWs infected on each day
    obs_sim1<-gen_observed_data(raw_sim1,prob_observing_patient_infection=1,prob_observing_hcw_infection=1)
    
    new_obs_sim1_weekly<-gen_wkly_total(obs_sim1)
    new_obs_sim1_weekly$trust<-trust_codes[i]
    obs_sim1_weekly<-rbind(obs_sim1_weekly,new_obs_sim1_weekly)
    
    new_obs_sim1_5dayweekly<-gen_wkly_total(obs_sim1, daysinweek = 5)
    new_obs_sim1_5dayweekly$trust<-trust_codes[i]
    obs_sim1_5dayweekly<-rbind(obs_sim1_5dayweekly,new_obs_sim1_5dayweekly)
  }
}
#  standata1<-obs_sim1_weekly
standata1<-obs_sim1_5dayweekly

standata1$ha_cases<-standata1$o_ha_P
standata1$ca_cases<-standata1$o_ca_P
standata1$hcw_cases<-standata1$o_total_H
standata1$hcw_cases_lag1<-NA
standata1$hcw_cases_lag2<-NA
standata1$ha_cases_lag1<-NA
standata1$ha_cases_lag2 <-NA
standata1$ca_cases_lag1<-NA
standata1$ca_cases_lag2<-NA

trusts<-unique(standata1$trust)
for(i in 1:length(trusts)){
  sel<-standata1$trust==trusts[i]
  sel.ind<-c(1:dim(standata1)[1])[sel]
  l<-length(sel.ind)
  
  standata1$hcw_cases_lag1[sel.ind[2:l]]<-standata1$o_total_H[sel.ind[1:(l-1)]]
  standata1$hcw_cases_lag2[sel.ind[3:l]]<-standata1$o_total_H[sel.ind[1:(l-2)]]
  
  
  standata1$ha_cases_lag1[sel.ind[2:l]]<-standata1$o_ha_P[sel.ind[1:(l-1)]]
  standata1$ha_cases_lag2[sel.ind[3:l]]<-standata1$o_ha_P[sel.ind[1:(l-2)]]
  
  standata1$ca_cases_lag1[sel.ind[2:l]]<-standata1$o_ca_P[sel.ind[1:(l-1)]]
  standata1$ca_cases_lag2[sel.ind[3:l]]<-standata1$o_ca_P[sel.ind[1:(l-2)]]

}

# strip out NAs (i.e. remove rows with NAs in lagged )


countNAs<-function(x){
  sum(is.na(x))
}

rowswithNAs<-apply(standata1,MARGIN = 1,FUN = countNAs)>0
standata1<-standata1[!rowswithNAs,]
# restrict to week 20 onwards
standata1<-standata1[standata1$week>19,]
# Now fit models in Stan 

sitrep_noso_covid_data <- list(
  N = dim(standata1)[1], #number of observations
  H = length(unique(standata1$trust)),  #number of trusts
  W = length(unique(standata1$week)),   #number of weeks
  #  now get trustindex for each record, starting from 1..
  
  trustindex = match(standata1$trust, unique(standata1$trust)),
  weekindex = match(standata1$week, unique(standata1$week)),
  ha1 = standata1$ha_cases,    #hospital acquired in patients
  lag1ha1 = standata1$ha_cases_lag1 ,
  lag2ha1 = standata1$ha_cases_lag2 ,

  lag1_ca = standata1$ca_cases_lag1,
  lag2_ca =standata1$ca_cases_lag2,
  hcw = standata1$hcw_cases,
  lag1hcw=standata1$hcw_cases_lag1,
  lag2hcw=standata1$hcw_cases_lag2
)

W <- length(unique(sitrep_noso_covid_data$weekindex))   #number of weeks
week<- 1:W
sitrep_noso_covid_data$week <- week

num_trusts<-sitrep_noso_covid_data$H

initial.values<-list(list(a=rep(0.1,num_trusts),a0=0.1, b0=0.1, c0=0.1, d0=0.1))
require("rstan")
modelP1.ha1.simdata <- stan(
  file = "ModelP1.ha1.simdata.stan",  
  data = sitrep_noso_covid_data,    # named list of data
  chains = 1,             # number of Markov chains
  init=initial.values,
  warmup = 500,          # number of warmup iterations per chain
  iter = 1000,            # total number of iterations per chain
  cores = 1,              # number of cores ( one per chain)
  thin=1,
  refresh = 100,
  seed= 42,
  #  control = list(max_treedepth = 15,adapt_delta=0.99),
  control = list(max_treedepth = 15,adapt_delta=0.99),
  verbose=FALSE
)
check_hmc_diagnostics(modelP1.ha1.simdata)

summary(modelP1.ha1.simdata ,pars=c("a0","b0","c0","d0","sigmasq_a","sigmasq_k","phi0", "k0"))
summary(modelP1.ha1.simdata ,pars=c("a0","ca_coeff","ha_coeff","hcw_coeff","sigmasq_a","phi0", "k0"))



plot_obs_v_fitted_by_trust(modelP1.ha1.simdata,sitrep_noso_covid_data)


# simplified version with no random effects or rescaled variables
initial.values<-list(list(a0=0.1, b0=0.1, c0=0.1, d0=0))

modelP1.ha1.simdatav2 <- stan(
  file = "ModelP1.ha1.simdatav2.stan",  
  data = sitrep_noso_covid_data,    # named list of data
  chains = 1,             # number of Markov chains
  init=initial.values,
  warmup = 500,          # number of warmup iterations per chain
  iter = 1000,            # total number of iterations per chain
  cores = 1,              # number of cores ( one per chain)
  thin=1,
  refresh = 100,
  seed= 42,
  #  control = list(max_treedepth = 15,adapt_delta=0.99),
  control = list(max_treedepth = 15,adapt_delta=0.99),
  verbose=FALSE
)
check_hmc_diagnostics(modelP1.ha1.simdatav2)

summary(plot_obs_v_fitted_by_trust ,pars=c("a0","b0","c0","d0","sigmasq_k","phi0", "k0"))
plot_obs_v_fitted_by_trust(plot_obs_v_fitted_by_trust,sitrep_noso_covid_data)  

# now just try standard nb regressions
require(MASS)
glm.nb(formula = ha_cases ~ ha_cases_lag1 ,data = standata1,link = "identity")
glm.nb(formula = ha_cases ~ ha_cases_lag1  + hcw_cases_lag1 ,data = standata1,link = "identity",start=c(0.02,0.7,0.1))
glm.nb(formula = ha_cases ~ ha_cases_lag1  + hcw_cases_lag1 +  ca_cases_lag1 ,data = standata1,link = "identity",start=c(0.02,0.7,0.1,0.1))



